### ISSUE TITLE
Synthetic Versions of Datasets [Not Released] ?

### ISSUE THREAD

**Issue by sidgairo18** [KupynOrest/instance_augmentation#1]
Dear authors, 
Great job on the work :)

Very excited to play around with it.
A quick query, the paper mentions that - "We also release fully synthetic and anonymized expansions for popular datasets: COCO, Pascal VOC and DUTS".

However on the first quick pass, I couldn't find the required files or link to these.

Would be great if you could please point to the above.

Thanks and regards,
Sid

**Comment by KupynOrest** [comment]
Hello,

Just added the links to the datasets

**Comment by sidgairo18** [comment]
Thanks a lot! :)
